# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

parameters:
- name: environment
  values:
  - sandpit
  - dev
  - prod
- name: app_name
  default: "terraform"

trigger:
- master

jobs:
- job: terraform_plan
  displayName: "terraform plan - ${{parammeters.environment}}"
  pool:
    vmImage: 'ubuntu-latest'
  variables:
  - group: "${{parameters.app_name}}_${{parameters.environment}}_secrets"
  - group: "${{parameters.app_name}}_${{parameters.environment}}_varables"

  steps:
  - task: InstallSSHKey
    displayName: 'Install a SSH key'
    inputs:
      knownHostEntry: 'blah'
      sshPublicKey: 'ssh blah'
      sshKeySecureFile: terraformmodules

  - task: RunScript
    - script: 
      displayName: 'Run a one-line script'
      echo "Hello, world! on ${{parameters.environment}}"

  - taek: RunScript2
    - script:
      displayName: 'Run a multi-line script'
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
    
