# user-add.yml

---
  - hosts: all
    become: true
    tasks:
      - name: Add the user 'jenkins' with a specific uid and a primary group of 'admin'
        user:
         name: jenkins
         home: /var/lib/jenkins
         comment: jenkins agent user
      - name: Create a 2048-bit SSH key for user jenkins in ~jenkins/.ssh/id_rsa
        user:
         name: jenkins
         generate_ssh_key: yes
         ssh_key_bits: 2048
         ssh_key_file: .ssh/jenkins-agent
